/*global INVENTORY_SIZE: true*/
INVENTORY_SIZE = 30;
/*global PLAYER_HEIGHT: true, PLAYER_WIDTH: true*/
PLAYER_HEIGHT = 90;
PLAYER_WIDTH = 30;
/*global MIN_WIDTH: true, MIN_HEIGHT: true, MAX_HEIGHT: true, MAX_FACTOR: true*/
MIN_WIDTH = 400;
MIN_HEIGHT = 200;
MAX_HEIGHT = 270;
MAX_FACTOR = 5;